#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=8:mem=64gb:ngpus=1
#PBS -q v1_gpu72
#PBS -N train_masking_model_subset
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate perturbgen
module load OpenMPI/4.1.6-GCC-13.2.0

# added this - update if i use a new API key 
# Supply WANDB_API_KEY through the job environment when logging online.
export WANDB_PROJECT="perturbgen_adipocytes"

# Remove DS_Store files before training
find /rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/ -name ".DS_Store" -delete


cd /rds/general/user/ap5625/home/perturbation_modeling/perturbGEN/subset_2k_adipocytes/
python train_masking_model_subset_adipocytes.py