project:
  perturbgen_directory: /gpfs/home/ap5625/add/Perturbgen

run:
  run_name: reproducing_LPS_pipeline
  results_root_directory: /gpfs/home/ap5625/add/pg_results

tokenize:
  gene_filtering_mode: hvg
  hvg_mode: before_tokenisation
  retained_obs_cols:
    - cell_type_harmonized
    - time_after_LPS
  pairing_mode: stratified
  time_obs_col: time_after_LPS
  main_pairing_obs: cell_type_harmonized
  optional_pairing_obs: []
  reference_time: normal
  time_point_order:
    - normal
    - 90m_LPS
    - 6h_LPS
    - 10h_LPS
  gene_median_dictionary_path: /gpfs/home/ap5625/add/data/gene_median_dict_gftokens_gc95M.pkl
  token_dictionary_path: /gpfs/home/ap5625/add/data/token_dict_gftokens_gc95M.pkl
  ensembl_mapping_path: /gpfs/home/ap5625/add/data/ensembl_mapping_dict_gc95M.pkl
  input_h5ad_path: /gpfs/home/ap5625/add/pg_results/reproducing_LPS_pipeline/full_lps.h5ad
  highly_variable_gene_count: 2000

model:
  encoder: scmaskgit
  encoder_checkpoint_path: /gpfs/home/ap5625/add/data/perturbgen_encoder.ckpt
  predicted_time_points:
    - 1
    - 2
    - 3
  retained_obs_cols:
    - cell_type_harmonized
    - time_after_LPS
  conditioning_obs_cols: []
  context_mode: true
  positional_encoding_mode: time_pos_sin
  model_dimension: 768
  transformer_layers: 6
  feedforward_dimension: 32
  num_nodes: 1
  random_seed: 0

masking:
  batch_size: 64
  epochs: 20
  learning_rate: 0.0001
  weight_decay: 0.0001
  data_loader_workers: 4
  mask_scheduler: pow
  use_weighted_sampler: false
  checkpoint_interval_epochs: 1
  resume_checkpoint_path: null

decoder:
  masking_checkpoint_path: null
  batch_size: 16
  epochs: 16
  count_learning_rate: 0.001
  count_weight_decay: 0.001
  masking_learning_rate: 0.0001
  masking_weight_decay: 0.0001
  masking_probability: 0.30
  count_dropout: 0.1
  data_loader_workers: 16
  loss_mode: zinb
  mask_scheduler: pow
  use_positional_encoding: false
  use_layer_normalization: true
  checkpoint_interval_epochs: 1

embedding:
  masking_checkpoint_path: null
  retained_obs_cols:
    - cell_pairing_index
    - time_after_LPS
    - cell_type_harmonized
  batch_size: 64
  data_loader_workers: 16
  return_cell_embeddings: true
  return_attention: false
  generate: false
  return_gene_embeddings: true
  gene_embedding_condition_obs: time_after_LPS
  masking_learning_rate: 0.0001
  masking_weight_decay: 0.0001
  count_learning_rate: 0.001
  count_weight_decay: 0.001
  mask_scheduler: pow

perturbation:
  decoder_checkpoint_path: null
  genes_to_perturb: []
  mode: mask
  sequence: src
  n_samples: 3
  batch_size: 16
  data_loader_workers: 16
  precision: 16
  context_mode: false

