#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=8:mem=64gb:ngpus=1
#PBS -q v1_gpu72
#PBS -N train_masking_model_hvg_adipocytes
eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate perturbgen
module load OpenMPI/4.1.6-GCC-13.2.0

# added this - update if i use a new API key 
export WANDB_API_KEY="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"
export WANDB_PROJECT="perturbgen_hvg_adipocytes"

# Remove DS_Store files before training
find /rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/ -name ".DS_Store" -delete


cd /rds/general/user/ap5625/home/perturbation_modeling/perturbGEN/adipocytes_HVG/train_masking_model
python train_masking_model_hvg_adipocytes.py