#!/bin/bash
#PBS -l walltime=72:00:00
#PBS -l select=1:ncpus=16:mem=64gb:ngpus=1
#PBS -q v1_gpu72
#PBS -N train_count_decoder_hvg
#PBS -o train_count_decoder_hvg.out
#PBS -e train_count_decoder_hvg.err

eval "$(~/miniforge3/bin/conda shell.bash hook)"
conda activate perturbgen
module load OpenMPI/4.1.6-GCC-13.2.0

# Supply WANDB_API_KEY through the job environment when logging online.
export WANDB_PROJECT="perturbgen_hvg_adipocytes"



# Add this before python command in train_decoder.pbs
find /rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/ -name ".DS_Store" -delete




cd /rds/general/user/ap5625/home/perturbation_modeling/perturbGEN/adipocytes_HVG/train_decoder

python train_count_decoder_hvg_adipocytes.py