data:
  src_dataset_file: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/T_perturb/tokenized_data/adipocytes_subset_obese_WL/dataset_all_src/obese.dataset" # path to src_dataset.dataset from tokenization step
  tgt_dataset_folder: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/T_perturb/tokenized_data/adipocytes_subset_obese_WL/dataset_all_tgt" # path to tgt_datasets_folder from tokenization step
  src_adata: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/T_perturb/tokenized_data/adipocytes_subset_obese_WL/h5ad_pairing_1462genes_src/obese.h5ad" # path to src_adata.h5ad from tokenization step
  tgt_adata_folder: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/T_perturb/tokenized_data/adipocytes_subset_obese_WL/h5ad_pairing_1462genes_tgt" # path to tgt_adata_folder from tokenization step-changed it to the subset object 
  cond_list:
    - "cell_states_adipocytes"  # list of condition columns used during training

trainer:
  use_count_decoder: true # whether to use the count decoder
  n_samples: 3 # number of samples to generate per input during inference
  tgt_vocab_size: 1464 # size of the target vocabulary (number of tokens) 
  d_model: 768 # dimension of the model
  generate: false # whether to generate perturbations
  use_positional_encoding: false # whether to use positional encoding
  dropout: 0 # dropout rate for prediction
  num_heads: 8 # number of attention heads
  num_layers: 6 # number of transformer layers
  loss_mode: "zinb" # loss function mode: "mse", "nb", "zinb"
  d_ff: 32 # dimension of the feedforward network
  max_seq_length: 381 # maximum sequence length - input the raw value - they then add 100 to that 
  mask_scheduler: "pow" # masking scheduler type
  output_dir: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/T_perturb/perturbation/perturbation_GFPT2_1462" # output directory for results - icreated it 
  mapping_dict_path: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/T_perturb/tokenized_data/adipocytes_subset_obese_WL/token_id_to_genename_all.pkl" # path to mapping dictionary from tokenization step
  tokenid_to_rowid_path: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/T_perturb/tokenized_data/adipocytes_subset_obese_WL/tokenid_to_rowid_all.pkl" # path to tokenid to rowid mapping from tokenization step
  encoder: "scmaskgit" # encoder type (Pretrain model)
  encoder_path: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/Perturbgen/pretraining_cohort/20250709_1223_cellgen_train_masking_lr_5e-05_wd_1e-06_batch_64_ptime_pos_sin_m_pow_tp_1-2-3_s_42-epoch=00.ckpt" # path to pretrained encoder weights
  context_mode: false # whether to use context mode, True is recommeneded for perturbation prediction of data with multiple time points
  temperature: 1.5 # temperature for generation
  iterations: 19 # number of generation iterations
  pos_encoding_mode: "time_pos_sin" # positional encoding mode
  exclude_src: false # whether to exclude source data during inference
  perturbation_mode: "mask" # perturbation mode: "mask" - this i can change depending on the type of perturbation i wanna do 
  genes_to_perturb:
    - "ENSG00000131459" # or gene name to perturb, here we give the model a list of genes to perturb - GFPT2 in this case 
  validation_mode: "inference" # validation mode: "inference"
  perturbation_sequence:
    - "src" # perturbation sequence: "src" or "tgt"
  var_list: # list of data.var retained during tokenization
    - "cell_states_adipocytes" 
    - "cell_pairing_index"
    - "condition"
  pred_tps: # time points to predict
    - 1


datamodule:
  batch_size: 64 # batch size for training
  num_workers: 8 # number of workers for data loading
  shuffle: false # whether to shuffle the data
  split: false # whether to split the data
  max_len: 381 # maximum sequence length - i find this by checking the src dataset 
  var_list: # list of data.var retained during tokenization, same as in trainer
    - "cell_states_adipocytes"
    - "condition"
    - "cell_pairing_index"
  pred_tps: # time points to predict/ perturb, same as in trainer - 
    - 1

model:
  precision: 16 # precision for training
  ckpt_masking_path: "/rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/T_perturb/res/count/checkpoints/20260609_1327_cellgen_train_count_lr_0.001_wd_0.001_batch_16_drop_0.1_zinb_tp_1_s_0_pos_time_pos_sin_m_cosine-epoch=14.ckpt" # path to count decoder checkpoint from previous count decoder training step (notebook 3)
