#!/bin/bash
#PBS -l walltime=18:00:00
#PBS -l select=1:ncpus=16:mem=300gb:cpu_type=icelake
#PBS -N tokenisation_full_adipocytes
#PBS -j oe

module load Python/3.11.5-GCCcore-13.2.0
export MKL_ENABLE_INSTRUCTIONS=AVX2

/rds/general/user/ap5625/home/.local/bin/poetry -C /rds/general/project/lms-scott-raw/live/Ada/perturbation_modeling/Perturbgen_clean/Perturbgen run python /rds/general/user/ap5625/home/perturbation_modeling/perturbGEN/full_adipocytes/tokenisation_full_adipocytes.py